export const ROUTES = {
    about: '/o-nas',
    cardigans: '/products/kardigany',
    contact: "/kontakt",
    delivery: '/koszt-dostawy',
    dresses: '/products/sukienki',
    email: 'info.kabarday@gmail.com',
    facebook: 'https://www.facebook.com/kabarday.fashion/',
    hats: '/products/czapki',
    instagram: 'https://www.instagram.com/kabarday.fashion/',
    jakZamowic: '/jak-zamowic',
    payment: '/metody-platnosci',
    privacyPolicy: '/polityka-prywatnosci',
    products: '/products',
    removeProduct: (id:string)=>`/products/${id}/remove`,
    policy: '/regulamin',
    realization: '/realizacja-zamowien',
    scarfs: '/products/szaliki',
    sweaters: '/products/swetry',
    trousers: '/products/spodnie',
    regulation: '/regulamin',
    website: 'https://kabarday.com',
}

